# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7fd0b0af7ab9003c5512df313fe7e40b051a3b4d902c15345471896baa1800e4d2021f4572706843772b714bf1dac77d562d3019072f05a4c93ca8feb4133f35

test:
  secret_key_base: a002956aec6f41669b67c8076def4c58321c2dacc1beaf42d802afe268ec178a0cb9122d12c1a1b2fea01e52f4206f4bbf1ab2c0ded43c7af49e3ded0cb31b5f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
